# Generated by Django 4.2 on 2024-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_f1ea2348-4092-4fac-bb7c-f4052d95611b', max_length=255, unique=True),
        ),
    ]
